services:
  - type: web
    name: aipt-web
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: flask db upgrade
    startCommand: gunicorn app:create_app
  - type: worker
    name: aipt-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A worker.celery worker --loglevel=info
databases:
  - name: redis
    ipAllowList: []
