services:
  - type: web
    name: aipt-web
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: flask --app app db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:                # ← 追加: OpenAI モデルを固定
      - key: OPENAI_MODEL
        value: gpt-4o-mini

  - type: worker
    name: aipt-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A worker.celery worker --loglevel=info

databases:
  - name: redis
    ipAllowList: []
