services:
  - type: web
    name: aipt-web
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: flask --app app db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    # OpenAI API キーは Render の Secret に設定してください
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY

  - # services:
#   - type: worker
#     name: aipt-worker
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: celery -A worker.celery worker --loglevel=info
databases:
  - name: redis
    ipAllowList: []
