services:
  - type: web
    name: aipt-web
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: flask --app app db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT "app:create_app()"
  - type: worker
    name: aipt-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A worker.celery worker --loglevel=info

databases:
  - name: redis
    ipAllowList: []
