name: Deploy to Xserver

on:
  push:
    branches:
      - main  # ← デプロイ対象ブランチを確認して変更OK

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to Xserver via SSH
      uses: appleboy/scp-action@v0.1.6
      with:
        host: 85.131.245.98
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/ver12-ai-posting-tool"
        
