name: Deploy to Xserver

on:
  push:
    branches:
      - main  # ← デプロイ対象ブランチを確認して変更OK

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to Xserver via SSH
      uses: appleboy/scp-action@v0.1.6
      with:
        host: 85.131.245.98
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/ver12-ai-posting-tool"

    - name: Install Python dependencies inside venv
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 85.131.245.98
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/ver12-ai-posting-tool
          ./venv/bin/pip install -r requirements.txt

    - name: Restart Flask App on Xserver
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 85.131.245.98
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # systemd ユニット更新を反映してから、web と jobs の2サービスを再起動
          sudo systemctl daemon-reload
          sudo systemctl restart ai-posting-web.service
          sudo systemctl restart ai-posting-jobs.service
          sudo systemctl --no-pager --full status ai-posting-web.service  | tail -n 80 || true
          sudo systemctl --no-pager --full status ai-posting-jobs.service | tail -n 80 || true
